import redirects from '../data/legacy-redirects.json'

// 301s from the OLD bimmerparts.nl URLs to the new site. The map is generated by
// scripts/legacy-redirects/build.py (see the README next to it).
const map = redirects as Record<string, string>

const normalize = (path: string) => {
  let p = path
  try { p = decodeURIComponent(p) } catch { /* keep raw */ }
  p = p.replace(/\.html$/i, '').replace(/\/+$/, '').toLowerCase()
  return p || '/'
}

export default defineEventHandler((event) => {
  if (event.method !== 'GET' && event.method !== 'HEAD') return

  const url = getRequestURL(event)
  const path = url.pathname
  // Skip Nuxt internals, API routes and static assets (anything with a file extension except .html)
  const isLegacyEntry = path.toLowerCase() === '/website/index.php'
  if (!isLegacyEntry && (path.startsWith('/_') || path.startsWith('/api/') || (/\.[a-z0-9]+$/i.test(path) && !/\.html$/i.test(path)))) return

  const key = normalize(path)
  let target = map[key]

  // Old platform category/pagination URLs: /website/index.php?ProductCategory=123&Index=4
  if (key === '/website/index.php') {
    const params = new Map([...url.searchParams].map(([k, v]) => [k.toLowerCase(), v]))
    const id = params.get('productcategory')
    if (id) target = map[`/website/index.php?productcategory=${id}`] ?? '/producten'
  }

  // Old shop's nested URLs, e.g. /Webwinkel-Product-123/Some-Product.html -> look up the last segment
  if (!target && key.startsWith('/webwinkel-product-')) target = map['/' + key.split('/').pop()]

  if (target && target !== path) return sendRedirect(event, target, 301)
})
